spring:
  application:
    name: spring-profile-demo
  profiles:
    active: prod
  config:
    import: "optional:classpath:/module/sys.yaml,\
    optional:classpath:/module/order.yaml"

server:
  port: 48791
