spring:
  application:
    name: spring-profile-demo
  profiles:
    active: prod
  config:
    import: "optional:classpath:/module/sys.yaml,\
    optional:classpath:/module/order.yaml"

app:
  info: |
    {
      "name": "spring-profile-demo",
      "version": "1.0.0"
    }

server:
  port: 48791
